// AUTO-GENERATED by scripts/generate-desktop-catalog.mjs — do not hand-edit.
// Source of truth: shared/shared.js TOOL_REGISTRY. Regenerate after any tool
// add/remove/rename: node scripts/generate-desktop-catalog.mjs
window.TOOLS_CATALOG = {
  totalTools: 96,
  collections: [
  {
    "id": "study",
    "label": "Study",
    "tools": [
      {
        "id": "cite",
        "label": "CiteMaker",
        "desc": "APA, MLA, Chicago, Harvard citations",
        "htmlPath": "study/cite/index.html"
      },
      {
        "id": "flashcards",
        "label": "FlashForge",
        "desc": "Flashcards with spaced repetition",
        "htmlPath": "study/flashcards/index.html"
      },
      {
        "id": "grades",
        "label": "GradeCalc",
        "desc": "GPA, weighted grade, final exam calculator",
        "htmlPath": "study/grades/index.html"
      },
      {
        "id": "bias",
        "label": "BiasCheck",
        "desc": "Media bias & loaded language analyser",
        "htmlPath": "study/bias/index.html"
      }
    ]
  },
  {
    "id": "write",
    "label": "Write",
    "tools": [
      {
        "id": "readscore",
        "label": "ReadScore",
        "desc": "Flesch-Kincaid readability analysis",
        "htmlPath": "write/readscore/index.html"
      },
      {
        "id": "wordcount",
        "label": "WordCount Pro",
        "desc": "Word count, keyword density, live",
        "htmlPath": "write/wordcount/index.html"
      },
      {
        "id": "lorem",
        "label": "LoremCraft",
        "desc": "Placeholder text in 10 styles",
        "htmlPath": "write/lorem/index.html"
      },
      {
        "id": "thread",
        "label": "ThreadCraft",
        "desc": "Split long text into a tweet thread",
        "htmlPath": "write/thread/index.html"
      }
    ]
  },
  {
    "id": "dev",
    "label": "Dev",
    "tools": [
      {
        "id": "json",
        "label": "JSONLab",
        "desc": "Format, validate, minify, diff JSON",
        "htmlPath": "dev/json/index.html"
      },
      {
        "id": "jsonconvert",
        "label": "JSONConvert",
        "desc": "JSON to YAML, CSV, XML, TOML",
        "htmlPath": "dev/jsonconvert/index.html"
      },
      {
        "id": "jwt",
        "label": "JWTStudio",
        "desc": "Decode & inspect JWT tokens",
        "htmlPath": "dev/jwt/index.html"
      },
      {
        "id": "yaml",
        "label": "YAMLCheck",
        "desc": "YAML validator & formatter",
        "htmlPath": "dev/yaml/index.html"
      },
      {
        "id": "csv",
        "label": "CSVExplore",
        "desc": "Sortable, filterable CSV viewer",
        "htmlPath": "dev/csv/index.html"
      },
      {
        "id": "markdown",
        "label": "MarkdownLive",
        "desc": "Markdown editor with live preview",
        "htmlPath": "dev/markdown/index.html"
      },
      {
        "id": "html",
        "label": "HTMLPreview",
        "desc": "Sandboxed HTML renderer",
        "htmlPath": "dev/html/index.html"
      },
      {
        "id": "sql",
        "label": "SQLFormat",
        "desc": "SQL formatter & beautifier",
        "htmlPath": "dev/sql/index.html"
      },
      {
        "id": "contrast",
        "label": "ColourContrast",
        "desc": "WCAG AA/AAA contrast checker",
        "htmlPath": "dev/contrast/index.html"
      },
      {
        "id": "uuid",
        "label": "UUIDGen",
        "desc": "UUID v4/v7, ULID, nanoid generator",
        "htmlPath": "dev/uuid/index.html"
      },
      {
        "id": "timezone",
        "label": "TimezoneNow",
        "desc": "World clock & meeting overlap finder",
        "htmlPath": "dev/timezone/index.html"
      },
      {
        "id": "timeconvert",
        "label": "TZConvert",
        "desc": "Convert a date & time across timezones",
        "htmlPath": "dev/timeconvert/index.html"
      },
      {
        "id": "regex",
        "label": "RegexLab",
        "desc": "Regex tester with match highlighting",
        "htmlPath": "dev/regex/index.html"
      },
      {
        "id": "cron",
        "label": "CronLab",
        "desc": "Cron expression workbench",
        "htmlPath": "dev/cron/index.html"
      },
      {
        "id": "base64",
        "label": "Base64Tool",
        "desc": "Encode and decode Base64 live — standard or URL-safe",
        "htmlPath": "dev/base64/index.html"
      },
      {
        "id": "diff",
        "label": "DiffCheck",
        "desc": "Line-by-line text comparison, fully local",
        "htmlPath": "dev/diff/index.html"
      },
      {
        "id": "websocket",
        "label": "WSTester",
        "desc": "Connect and test WebSocket servers from your browser",
        "htmlPath": "dev/websocket/index.html"
      },
      {
        "id": "play",
        "label": "CodePlay",
        "desc": "HTML/CSS/JS playground with live preview and console",
        "htmlPath": "dev/play/index.html"
      },
      {
        "id": "bigo",
        "label": "BigOCheck",
        "desc": "Estimate time complexity from code structure",
        "htmlPath": "dev/bigo/index.html"
      },
      {
        "id": "worldclock",
        "label": "WorldClock",
        "desc": "Airport-style analog world clocks, TV fullscreen",
        "htmlPath": "dev/worldclock/index.html"
      },
      {
        "id": "timestamp",
        "label": "TimestampConvert",
        "desc": "Unix timestamp <-> date, live, across timezones",
        "htmlPath": "dev/timestamp/index.html"
      },
      {
        "id": "jsoncsv",
        "label": "JSONCSV",
        "desc": "Convert JSON arrays to CSV and back",
        "htmlPath": "dev/jsoncsv/index.html"
      },
      {
        "id": "hashgen",
        "label": "HashGen",
        "desc": "SHA-1/256/384/512 hashes for text or files",
        "htmlPath": "dev/hashgen/index.html"
      },
      {
        "id": "keygen",
        "label": "KeyGen",
        "desc": "RSA/ECDSA keypair generator, exported as PEM",
        "htmlPath": "dev/keygen/index.html"
      },
      {
        "id": "passhash",
        "label": "PassHash",
        "desc": "Hash and verify passwords with real bcrypt/Argon2id (WASM)",
        "htmlPath": "dev/passhash/index.html"
      },
      {
        "id": "svgclean",
        "label": "SVGClean",
        "desc": "Strip editor cruft, comments, and excess precision from SVG markup",
        "htmlPath": "dev/svgclean/index.html"
      },
      {
        "id": "sqlobfuscate",
        "label": "SQLObfuscate",
        "desc": "Anonymize table/column names and literals in a SQL query",
        "htmlPath": "dev/sqlobfuscate/index.html"
      }
    ]
  },
  {
    "id": "data",
    "label": "Data & AI",
    "tools": [
      {
        "id": "schema",
        "label": "SchemaViz",
        "desc": "SQL DDL to an interactive ER diagram — MySQL, Postgres, SQLite, SQL Server",
        "htmlPath": "data/schema/index.html"
      },
      {
        "id": "notebook",
        "label": "NotebookView",
        "desc": "Open a Jupyter .ipynb with plots, tables and tracebacks intact",
        "htmlPath": "data/notebook/index.html"
      },
      {
        "id": "vector",
        "label": "VectorLens",
        "desc": "Visualise embeddings — PCA projection, clusters and cosine search",
        "htmlPath": "data/vector/index.html"
      },
      {
        "id": "dataset",
        "label": "DataSetInspect",
        "desc": "Validate a fine-tuning JSONL — bad rows, duplicates, length outliers",
        "htmlPath": "data/dataset/index.html"
      }
    ]
  },
  {
    "id": "marketing",
    "label": "Marketing",
    "tools": [
      {
        "id": "utm",
        "label": "UTMBuilder",
        "desc": "Build UTM tracking links — history saved locally",
        "htmlPath": "marketing/utm/index.html"
      },
      {
        "id": "headline",
        "label": "HeadlineScore",
        "desc": "Score headlines for clarity, emotion, and SEO",
        "htmlPath": "marketing/headline/index.html"
      },
      {
        "id": "emailsubject",
        "label": "EmailSubjectTester",
        "desc": "Spam triggers, mobile preview, sentiment",
        "htmlPath": "marketing/emailsubject/index.html"
      },
      {
        "id": "adcopy",
        "label": "AdCopyWriter",
        "desc": "Google, Meta and LinkedIn ad copy from a brief",
        "htmlPath": "marketing/adcopy/index.html"
      },
      {
        "id": "calendar",
        "label": "SocialCalendar",
        "desc": "Plan your content calendar — saved locally",
        "htmlPath": "marketing/calendar/index.html"
      },
      {
        "id": "persona",
        "label": "PersonaBuilder",
        "desc": "AI-assisted customer personas, saved locally",
        "htmlPath": "marketing/persona/index.html"
      },
      {
        "id": "competitor",
        "label": "CompetitorMatrix",
        "desc": "Feature comparison matrix — export CSV or Markdown",
        "htmlPath": "marketing/competitor/index.html"
      },
      {
        "id": "roi",
        "label": "ROICalculator",
        "desc": "ROI, ROAS, CPA, CLV and payback period",
        "htmlPath": "marketing/roi/index.html"
      }
    ]
  },
  {
    "id": "finance",
    "label": "Finance",
    "tools": [
      {
        "id": "compound",
        "label": "CompoundCalc",
        "desc": "Compound interest with monthly contributions",
        "htmlPath": "finance/compound/index.html"
      },
      {
        "id": "budget",
        "label": "BudgetPlanner",
        "desc": "50/30/20 budget split with a donut chart",
        "htmlPath": "finance/budget/index.html"
      },
      {
        "id": "mortgage",
        "label": "MortgageCalc",
        "desc": "EMI, amortisation schedule, overpayment savings",
        "htmlPath": "finance/mortgage/index.html"
      },
      {
        "id": "investments",
        "label": "InvestmentTracker",
        "desc": "Portfolio holdings, returns, and allocation",
        "htmlPath": "finance/investments/index.html"
      },
      {
        "id": "tax",
        "label": "TaxEstimate",
        "desc": "Income tax for India, US or UK",
        "htmlPath": "finance/tax/index.html"
      },
      {
        "id": "currency",
        "label": "CurrencyConvert",
        "desc": "170+ currencies — rates cached daily",
        "htmlPath": "finance/currency/index.html"
      },
      {
        "id": "equity",
        "label": "EquityCalc",
        "desc": "Cap table dilution across funding rounds",
        "htmlPath": "finance/equity/index.html"
      },
      {
        "id": "networth",
        "label": "NetWorthTracker",
        "desc": "Assets minus liabilities, tracked monthly",
        "htmlPath": "finance/networth/index.html"
      },
      {
        "id": "loan",
        "label": "LoanCalc",
        "desc": "EMI, amortisation, and part-payment impact for any loan",
        "htmlPath": "finance/loan/index.html"
      },
      {
        "id": "retire",
        "label": "RetireCalc",
        "desc": "Retirement corpus needed vs on track — and the gap",
        "htmlPath": "finance/retire/index.html"
      },
      {
        "id": "inflation",
        "label": "InflationCalc",
        "desc": "What inflation does to your money over time",
        "htmlPath": "finance/inflation/index.html"
      }
    ]
  },
  {
    "id": "legal",
    "label": "Legal",
    "tools": [
      {
        "id": "contract",
        "label": "ContractRead",
        "desc": "Plain-English contract summary — on-device AI",
        "htmlPath": "legal/contract/index.html"
      },
      {
        "id": "nda",
        "label": "NDAGenerator",
        "desc": "Mutual or one-way NDA from a template",
        "htmlPath": "legal/nda/index.html"
      },
      {
        "id": "privacy-policy",
        "label": "PrivacyPolicyGen",
        "desc": "GDPR/CCPA-aware privacy policy generator",
        "htmlPath": "legal/privacy-policy/index.html"
      },
      {
        "id": "terms",
        "label": "TermsBuilder",
        "desc": "Terms of Service from a template",
        "htmlPath": "legal/terms/index.html"
      },
      {
        "id": "copyright",
        "label": "CopyrightChecker",
        "desc": "Estimate public-domain status by jurisdiction",
        "htmlPath": "legal/copyright/index.html"
      },
      {
        "id": "glossary",
        "label": "LegalGlossary",
        "desc": "130+ legal terms explained in plain English",
        "htmlPath": "legal/glossary/index.html"
      }
    ]
  },
  {
    "id": "hr",
    "label": "HR",
    "tools": [
      {
        "id": "salary",
        "label": "SalaryBand",
        "desc": "Pay grades, compa-ratio, range visualisation",
        "htmlPath": "hr/salary/index.html"
      },
      {
        "id": "jd",
        "label": "JobDescriptionWriter",
        "desc": "Inclusive job descriptions via on-device AI",
        "htmlPath": "hr/jd/index.html"
      },
      {
        "id": "interview",
        "label": "InterviewKit",
        "desc": "Role-specific questions and a scoring rubric",
        "htmlPath": "hr/interview/index.html"
      },
      {
        "id": "offer",
        "label": "OfferLetterBuilder",
        "desc": "Professional offer letter from a template",
        "htmlPath": "hr/offer/index.html"
      },
      {
        "id": "onboarding",
        "label": "OnboardingChecklist",
        "desc": "Day 1 / Week 1 / Month 1 checklist, saved locally",
        "htmlPath": "hr/onboarding/index.html"
      },
      {
        "id": "leave",
        "label": "LeaveCalculator",
        "desc": "Accrual, balance, and carry-forward",
        "htmlPath": "hr/leave/index.html"
      }
    ]
  },
  {
    "id": "health",
    "label": "Health",
    "tools": [
      {
        "id": "bmi",
        "label": "BMICalc",
        "desc": "BMI, BMR, TDEE and healthy weight range",
        "htmlPath": "health/bmi/index.html"
      },
      {
        "id": "medication",
        "label": "MedicationLog",
        "desc": "Medications, doses and adherence rate",
        "htmlPath": "health/medication/index.html"
      },
      {
        "id": "symptoms",
        "label": "SymptomDiary",
        "desc": "Log symptoms and severity on a calendar",
        "htmlPath": "health/symptoms/index.html"
      },
      {
        "id": "cycle",
        "label": "CycleTracker",
        "desc": "Predict next period and fertile window",
        "htmlPath": "health/cycle/index.html"
      },
      {
        "id": "water",
        "label": "WaterIntake",
        "desc": "One-tap hydration logging and streaks",
        "htmlPath": "health/water/index.html"
      },
      {
        "id": "sleep",
        "label": "SleepLog",
        "desc": "Sleep duration, quality and AI pattern analysis",
        "htmlPath": "health/sleep/index.html"
      }
    ]
  },
  {
    "id": "design",
    "label": "Design",
    "tools": [
      {
        "id": "sketch",
        "label": "SketchPad",
        "desc": "Local whiteboard — pen, shapes, arrows, text, PNG export",
        "htmlPath": "design/sketch/index.html"
      },
      {
        "id": "photo",
        "label": "PhotoTune",
        "desc": "Local photo editor — filters, rotate, resize, export",
        "htmlPath": "design/photo/index.html"
      },
      {
        "id": "palette",
        "label": "PaletteForge",
        "desc": "Colour palettes with CSS/Tailwind export and contrast ratios",
        "htmlPath": "design/palette/index.html"
      },
      {
        "id": "typography",
        "label": "TypographyScale",
        "desc": "A harmonious 9-step type scale from base size and ratio",
        "htmlPath": "design/typography/index.html"
      },
      {
        "id": "icons",
        "label": "IconExplorer",
        "desc": "A curated outline icon set — copy as SVG, JSX, or Vue",
        "htmlPath": "design/icons/index.html"
      },
      {
        "id": "shadows",
        "label": "ShadowStudio",
        "desc": "Layered CSS box shadows visually, with presets",
        "htmlPath": "design/shadows/index.html"
      },
      {
        "id": "spacing",
        "label": "SpacingCalc",
        "desc": "Linear or multiplicative spacing scale, with export",
        "htmlPath": "design/spacing/index.html"
      },
      {
        "id": "gradient",
        "label": "GradientMaker",
        "desc": "Linear, radial, and conic CSS gradients visually",
        "htmlPath": "design/gradient/index.html"
      },
      {
        "id": "imagecompress",
        "label": "ImageCompress",
        "desc": "Resize and recompress images locally — JPEG/WebP/PNG",
        "htmlPath": "design/imagecompress/index.html"
      }
    ]
  },
  {
    "id": "productivity",
    "label": "Productivity",
    "tools": [
      {
        "id": "convert",
        "label": "UnitConvert",
        "desc": "Every common unit converted live, with full tables",
        "htmlPath": "productivity/convert/index.html"
      },
      {
        "id": "focus",
        "label": "FocusTimer",
        "desc": "Pomodoro-style focus sessions with notifications",
        "htmlPath": "productivity/focus/index.html"
      },
      {
        "id": "note",
        "label": "QuickNote",
        "desc": "A fast, private notepad that autosaves as you type",
        "htmlPath": "productivity/note/index.html"
      },
      {
        "id": "decision",
        "label": "DecisionMatrix",
        "desc": "Weigh criteria, rate options, see which wins",
        "htmlPath": "productivity/decision/index.html"
      },
      {
        "id": "meeting-timer",
        "label": "MeetingTimer",
        "desc": "See the real cost of your meeting, live",
        "htmlPath": "productivity/meeting-timer/index.html"
      },
      {
        "id": "habits",
        "label": "HabitTracker",
        "desc": "Daily habits with streaks and a heatmap",
        "htmlPath": "productivity/habits/index.html"
      },
      {
        "id": "reading",
        "label": "ReadingList",
        "desc": "Save articles and books, track status and notes",
        "htmlPath": "productivity/reading/index.html"
      }
    ]
  },
  {
    "id": "ai",
    "label": "Chrome AI",
    "tools": [
      {
        "id": "summarize",
        "label": "AISummarize",
        "desc": "Summarize long text on-device — TL;DR, key points, headline",
        "htmlPath": "ai/summarize/index.html"
      },
      {
        "id": "translate",
        "label": "AITranslate",
        "desc": "Translate between languages on-device with auto-detection",
        "htmlPath": "ai/translate/index.html"
      },
      {
        "id": "write",
        "label": "AIWrite",
        "desc": "Draft an email, post, or message from bullet points — on-device",
        "htmlPath": "ai/write/index.html"
      },
      {
        "id": "rewrite",
        "label": "AIRewrite",
        "desc": "Change the tone or length of text — on-device",
        "htmlPath": "ai/rewrite/index.html"
      }
    ]
  }
],
};
