// LegalGlossary — bundled data, no AI needed. ~130 common legal terms.
const GLOSSARY_TERMS = [
  ['Indemnification', 'One party agrees to compensate the other for certain losses or damages.', 'The vendor indemnifies the client against claims arising from its own negligence.'],
  ['Force Majeure', 'A clause excusing a party from performance due to extraordinary events beyond its control.', 'The pandemic triggered the force majeure clause, suspending delivery deadlines.'],
  ['Consideration', 'Something of value exchanged between parties that makes a contract legally binding.', 'The $1 payment was nominal consideration to make the option agreement enforceable.'],
  ['Breach of Contract', 'Failing to perform a duty or obligation specified in a contract.', 'Missing the delivery date by three weeks was a material breach of contract.'],
  ['Liquidated Damages', 'A pre-agreed sum payable if a party breaches the contract, in place of proving actual loss.', 'The construction contract set liquidated damages of $500 per day of delay.'],
  ['Non-Disclosure Agreement (NDA)', 'A contract requiring one or both parties to keep shared information confidential.', 'Before sharing the prototype, both companies signed a mutual NDA.'],
  ['Non-Compete Clause', 'A provision restricting a person from working for competitors for a period of time.', 'Her non-compete clause prevented her from joining a rival firm for one year.'],
  ['Governing Law', 'The jurisdiction whose laws will be used to interpret a contract.', 'The agreement specifies that the governing law is the State of Delaware.'],
  ['Arbitration', 'A private dispute-resolution process where a neutral arbitrator issues a binding decision.', 'Instead of going to court, the parties resolved the dispute through arbitration.'],
  ['Mediation', 'A non-binding process where a neutral third party helps parties reach a voluntary settlement.', 'They tried mediation before escalating to a lawsuit.'],
  ['Severability', 'A clause stating that if one part of a contract is invalid, the rest remains enforceable.', 'Thanks to the severability clause, striking one illegal term didn’t void the whole agreement.'],
  ['Indemnitor', 'The party that agrees to compensate another for loss (the one giving indemnification).', 'As the indemnitor, the contractor covered the cost of the third-party claim.'],
  ['Indemnitee', 'The party protected by an indemnification clause.', 'The client, as indemnitee, was reimbursed for the legal fees.'],
  ['Waiver', 'The voluntary giving up of a known legal right.', 'By not enforcing the late fee for months, the landlord may have created a waiver.'],
  ['Assignment', 'Transferring rights or obligations under a contract to another party.', 'The lease permitted assignment to a subsidiary with the landlord’s consent.'],
  ['Novation', 'Replacing one party in a contract with a new party, extinguishing the original party’s obligations.', 'Through novation, the new supplier stepped into all rights and duties of the old one.'],
  ['Termination for Convenience', 'A clause allowing a party to end the contract without cause, usually with notice.', 'The client exercised termination for convenience after 30 days’ notice.'],
  ['Termination for Cause', 'Ending a contract due to the other party’s breach or default.', 'The vendor was terminated for cause after repeated missed deadlines.'],
  ['Statute of Limitations', 'The maximum time after an event within which legal proceedings may be initiated.', 'The statute of limitations for the claim expired after four years.'],
  ['Jurisdiction', 'The authority of a court to hear and decide a case.', 'The contract designates the courts of New York as having exclusive jurisdiction.'],
  ['Venue', 'The specific geographic location where a case will be tried.', 'The parties agreed the venue for any dispute would be San Francisco County.'],
  ['Tort', 'A civil wrong that causes harm, giving rise to legal liability.', 'Negligence, defamation, and trespass are all types of tort.'],
  ['Negligence', 'Failure to exercise reasonable care, resulting in harm to another.', 'The store was found liable for negligence after failing to clean up a spill.'],
  ['Liability', 'Legal responsibility for one’s acts or omissions.', 'The driver was held liable for the damages caused by the collision.'],
  ['Limitation of Liability', 'A clause capping the amount of damages one party can recover from another.', 'The SaaS agreement limited liability to fees paid in the prior 12 months.'],
  ['Indemnity Cap', 'A ceiling placed on the total amount owed under an indemnification obligation.', 'The parties negotiated an indemnity cap equal to two times the contract value.'],
  ['Representations and Warranties', 'Statements of fact and promises made by a party that the other party relies on.', 'The seller made representations and warranties about the company’s financial condition.'],
  ['Covenant', 'A formal promise to do or not do a particular act.', 'The loan agreement included a covenant not to take on additional debt.'],
  ['Condition Precedent', 'An event that must occur before a contractual obligation becomes due.', 'Closing was a condition precedent to the release of escrow funds.'],
  ['Boilerplate', 'Standard contract language used repeatedly with little or no variation.', 'The notices and governing law sections were standard boilerplate.'],
  ['Recital', 'Introductory statements in a contract explaining its background and purpose.', 'The recitals explained that the parties had previously worked together on Project X.'],
  ['Execution', 'The act of signing a document to make it legally effective.', 'The merger agreement was ready for execution by both CEOs.'],
  ['Counterpart', 'One of multiple identical copies of a document, each considered an original.', 'The contract was signed in counterparts by parties in different countries.'],
  ['Escrow', 'Money or documents held by a neutral third party until conditions are met.', 'The buyer’s deposit was held in escrow until the inspection was complete.'],
  ['Due Diligence', 'A thorough investigation of a business or person before entering into an agreement.', 'The acquirer conducted due diligence on the target’s finances and contracts.'],
  ['Fiduciary Duty', 'A legal obligation to act in the best interest of another party.', 'As a director, she owed a fiduciary duty to the company’s shareholders.'],
  ['Power of Attorney', 'A legal document authorizing someone to act on another’s behalf.', 'He granted his sister power of attorney while he was overseas.'],
  ['Injunction', 'A court order requiring a party to do or refrain from doing a specific act.', 'The court issued an injunction preventing the ex-employee from contacting clients.'],
  ['Cease and Desist', 'A demand that a party stop an allegedly unlawful activity.', 'The trademark owner sent a cease and desist letter over the copied logo.'],
  ['Class Action', 'A lawsuit filed by one or more plaintiffs on behalf of a larger group with similar claims.', 'Thousands of customers joined the class action over the data breach.'],
  ['Plaintiff', 'The party who initiates a lawsuit.', 'The plaintiff alleged that the company breached its warranty obligations.'],
  ['Defendant', 'The party being sued or accused in a legal proceeding.', 'The defendant denied all allegations in its response.'],
  ['Discovery', 'The pre-trial process of exchanging information between parties in a lawsuit.', 'During discovery, both sides exchanged thousands of emails.'],
  ['Deposition', 'Sworn out-of-court testimony given as part of the discovery process.', 'The witness answered questions for six hours during her deposition.'],
  ['Subpoena', 'A legal order requiring a person to testify or produce documents.', 'The company received a subpoena for its financial records.'],
  ['Settlement', 'An agreement resolving a dispute without going to trial.', 'The parties reached a settlement two days before the trial date.'],
  ['Damages', 'Monetary compensation awarded for loss or injury.', 'The jury awarded $2 million in damages to the plaintiff.'],
  ['Punitive Damages', 'Damages intended to punish a wrongdoer, beyond compensating actual loss.', 'The court awarded punitive damages due to the defendant’s reckless conduct.'],
  ['Compensatory Damages', 'Damages meant to compensate for actual loss suffered.', 'Compensatory damages covered the plaintiff’s medical bills and lost wages.'],
  ['Consequential Damages', 'Indirect losses that result from a breach, beyond direct damages.', 'The contract excluded consequential damages such as lost profits.'],
  ['Indefeasible', 'Not able to be made void, undone, or annulled.', 'The buyer obtained indefeasible title to the property after the sale.'],
  ['Estoppel', 'A legal principle preventing a party from contradicting its earlier statements or actions.', 'The tenant was barred by estoppel from denying the lease term he’d relied on.'],
  ['Good Faith', 'Honesty of intention and fair dealing in performing a contract.', 'Both parties are required to negotiate the renewal in good faith.'],
  ['Material Breach', 'A significant failure to perform that undermines the purpose of the contract.', 'Failing to deliver the core product was a material breach, not a minor one.'],
  ['Boilerplate Clause: Entire Agreement', 'States that the written contract represents the complete agreement, superseding prior discussions.', 'The entire agreement clause meant earlier verbal promises were not enforceable.'],
  ['Confidential Information', 'Information designated as private that a receiving party agrees not to disclose.', 'Product roadmaps were defined as confidential information under the NDA.'],
  ['Intellectual Property (IP)', 'Legal rights over creations of the mind, such as inventions, designs, and works.', 'The startup’s main asset was its intellectual property, including three patents.'],
  ['Copyright', 'Legal protection for original works of authorship, such as writing, music, or software.', 'The author holds the copyright to the novel for her lifetime plus 70 years.'],
  ['Trademark', 'A word, symbol, or design that identifies and distinguishes a source of goods or services.', 'The company registered its logo as a trademark.'],
  ['Patent', 'An exclusive right granted for an invention, preventing others from making or selling it.', 'The inventor filed a patent for the new battery technology.'],
  ['Trade Secret', 'Confidential business information that provides a competitive edge.', 'The soda formula is protected as a trade secret rather than a patent.'],
  ['License', 'Permission granted to use property or intellectual property under specified conditions.', 'The software is provided under a limited, non-exclusive license.'],
  ['Royalty', 'A payment made for the ongoing use of intellectual property.', 'The author receives a 10% royalty on each book sold.'],
  ['Public Domain', 'Works or inventions not protected by intellectual property rights, free for anyone to use.', 'Shakespeare’s plays are in the public domain.'],
  ['Fair Use', 'A legal doctrine permitting limited use of copyrighted material without permission.', 'Quoting a short passage for a book review generally qualifies as fair use.'],
  ['Work for Hire', 'Work created by an employee or contractor that is owned by the employer, not the creator.', 'The freelance logo design was a work for hire owned by the client.'],
  ['Terms of Service', 'The rules users agree to follow when using a website or app.', 'Uploading pirated content violates the platform’s terms of service.'],
  ['Privacy Policy', 'A document explaining how an organization collects, uses, and protects personal data.', 'The privacy policy discloses that analytics data is shared with a third party.'],
  ['GDPR', 'The EU’s General Data Protection Regulation, governing personal data privacy.', 'Under GDPR, users can request that their personal data be deleted.'],
  ['CCPA', 'The California Consumer Privacy Act, granting California residents data privacy rights.', 'CCPA gives consumers the right to opt out of the sale of their data.'],
  ['Data Controller', 'The entity that determines the purposes and means of processing personal data.', 'As the data controller, the company decides how customer data is used.'],
  ['Data Processor', 'An entity that processes personal data on behalf of a data controller.', 'The cloud hosting company acts as a data processor for its clients.'],
  ['Personally Identifiable Information (PII)', 'Data that can be used to identify a specific individual.', 'Names, emails, and Social Security numbers are all PII.'],
  ['Opt-In', 'A consent model where a user must actively agree before data is collected or used.', 'The newsletter required an opt-in checkbox before signup.'],
  ['Opt-Out', 'A consent model where data collection continues unless the user actively declines.', 'Users can opt out of targeted advertising in their account settings.'],
  ['Limited Liability Company (LLC)', 'A business structure that limits owners’ personal liability for company debts.', 'She formed an LLC to protect her personal assets from business liabilities.'],
  ['Sole Proprietorship', 'A business owned and run by one person, with no legal distinction from the owner.', 'As a sole proprietorship, he was personally liable for all business debts.'],
  ['Corporation', 'A legal entity separate from its owners, offering liability protection to shareholders.', 'The founders incorporated as a Delaware C-Corporation.'],
  ['Articles of Incorporation', 'The founding document that creates a corporation under state law.', 'The articles of incorporation listed the company’s name and purpose.'],
  ['Bylaws', 'Internal rules governing how a corporation is managed and operated.', 'The bylaws set out how often the board of directors must meet.'],
  ['Board of Directors', 'A group elected to oversee the management of a corporation.', 'The board of directors approved the acquisition unanimously.'],
  ['Shareholder', 'A person or entity that owns shares in a corporation.', 'Shareholders vote on major decisions at the annual meeting.'],
  ['Cap Table', 'A record of a company’s ownership, showing equity stakes of founders and investors.', 'The cap table showed the founders retained 60% ownership after the round.'],
  ['Vesting', 'The process by which an employee earns full rights to equity or benefits over time.', 'Her stock options vest over four years with a one-year cliff.'],
  ['Cliff', 'A vesting provision requiring a minimum period of service before any equity vests.', 'Because of the one-year cliff, he received no equity when he left after eight months.'],
  ['Dilution', 'The reduction in existing shareholders’ ownership percentage after new shares are issued.', 'The new funding round caused 20% dilution for early investors.'],
  ['Term Sheet', 'A non-binding document outlining the key terms of a proposed investment or deal.', 'The VC firm sent a term sheet offering $2 million for 15% equity.'],
  ['Convertible Note', 'A short-term loan that converts into equity, typically at a future financing round.', 'The startup raised its first $500,000 through a convertible note.'],
  ['SAFE (Simple Agreement for Future Equity)', 'An investment contract granting the right to future equity without being a loan.', 'The angel investor used a SAFE instead of a convertible note.'],
  ['Preferred Stock', 'Shares with priority over common stock for dividends and liquidation proceeds.', 'Investors typically receive preferred stock with liquidation preference.'],
  ['Common Stock', 'Standard company shares typically held by founders and employees.', 'Employees are usually granted options to purchase common stock.'],
  ['Liquidation Preference', 'The right of certain shareholders to be paid before others when a company is sold.', 'With a 1x liquidation preference, investors get their money back first.'],
  ['Drag-Along Rights', 'A provision forcing minority shareholders to join a sale approved by the majority.', 'Drag-along rights ensured all shareholders sold when the majority agreed to the acquisition.'],
  ['Tag-Along Rights', 'A provision allowing minority shareholders to join a sale on the same terms as majority holders.', 'Tag-along rights let the small investor sell alongside the founders.'],
  ['Right of First Refusal (ROFR)', 'The right to match any offer before shares can be sold to a third party.', 'The company exercised its right of first refusal to buy back the departing employee’s shares.'],
  ['At-Will Employment', 'An employment arrangement where either party can end it at any time, for any legal reason.', 'As an at-will employee, she could resign without giving notice.'],
  ['Non-Solicitation Clause', 'A provision preventing a former employee from recruiting clients or staff.', 'The non-solicitation clause barred him from poaching his old team for a year.'],
  ['Severance', 'Pay or benefits given to an employee upon termination.', 'She negotiated three months of severance as part of her exit.'],
  ['Wrongful Termination', 'Firing an employee in violation of law or contract.', 'He filed a claim for wrongful termination after being fired for whistleblowing.'],
  ['Independent Contractor', 'A self-employed person who provides services under a contract, not as an employee.', 'The company hired her as an independent contractor to avoid payroll obligations.'],
  ['Misclassification', 'Incorrectly labeling a worker as a contractor when they should be an employee.', 'The gig company faced a lawsuit over misclassification of drivers.'],
  ['Garden Leave', 'A period where a departing employee is paid but not required to work, often before joining a competitor.', 'His contract included six months of garden leave before he could start his new job.'],
  ['Probate', 'The legal process of administering a deceased person’s estate.', 'The house couldn’t be sold until it cleared probate.'],
  ['Testator', 'A person who has made a valid will.', 'The testator left specific instructions for dividing the estate.'],
  ['Executor', 'A person appointed to carry out the instructions of a will.', 'His sister was named executor of their father’s estate.'],
  ['Beneficiary', 'A person entitled to receive assets or benefits under a will, trust, or policy.', 'The grandchildren were named as beneficiaries of the trust.'],
  ['Trust', 'A legal arrangement where assets are held by one party for the benefit of another.', 'The parents set up a trust to fund their children’s education.'],
  ['Intestate', 'Dying without a valid will.', 'Because he died intestate, state law determined how his assets were distributed.'],
  ['Power of Sale', 'A clause allowing a lender to sell mortgaged property without court approval upon default.', 'The bank exercised its power of sale after the homeowner missed payments.'],
  ['Easement', 'A legal right to use another person’s land for a specific purpose.', 'The neighbor had an easement to use the shared driveway.'],
  ['Title', 'Legal ownership of property.', 'A title search confirmed there were no liens on the house.'],
  ['Lien', 'A legal claim against property as security for a debt.', 'The contractor placed a lien on the house after the client didn’t pay.'],
  ['Encumbrance', 'A claim or liability attached to property, such as a lien or easement.', 'The buyer required all encumbrances to be cleared before closing.'],
  ['Zoning', 'Government regulations restricting how land in a specific area can be used.', 'Zoning rules prevented the plot from being used for commercial purposes.'],
  ['Eminent Domain', 'The government’s power to take private property for public use, with compensation.', 'The city used eminent domain to build the new highway.'],
  ['Chain of Title', 'The historical sequence of ownership transfers for a piece of property.', 'The title company traced the chain of title back fifty years.'],
  ['Amicus Brief', 'A legal document filed by a non-party offering information relevant to a case.', 'Several advocacy groups filed amicus briefs supporting the appeal.'],
  ['Affidavit', 'A written statement made under oath, used as evidence.', 'She submitted an affidavit confirming she witnessed the signing.'],
  ['Notary Public', 'An official authorized to witness signatures and administer oaths.', 'The deed had to be signed in front of a notary public.'],
  ['Habeas Corpus', 'A legal action requiring a person under arrest to be brought before a court.', 'His lawyers filed a writ of habeas corpus challenging his detention.'],
  ['Pro Bono', 'Legal work performed voluntarily and without payment, for the public good.', 'The law firm took the immigration case pro bono.'],
  ['Retainer', 'An upfront fee paid to secure a lawyer’s services.', 'The client paid a $5,000 retainer before work began.'],
  ['Statute', 'A written law enacted by a legislative body.', 'The new statute raised the minimum wage statewide.'],
  ['Regulation', 'A rule issued by a government agency to implement or enforce a statute.', 'The agency issued a regulation clarifying data-retention requirements.'],
  ['Precedent', 'A previous court decision that guides future rulings on similar issues.', 'The judge cited precedent from a similar case decided a decade earlier.'],
  ['Summary Judgment', 'A court ruling made without a full trial because there is no genuine factual dispute.', 'The judge granted summary judgment in favor of the defendant.'],
  ['Appeal', 'A request to a higher court to review and change the outcome of a lower court’s decision.', 'The losing party filed an appeal within thirty days of the ruling.'],
  ['Consent Decree', 'A court-approved settlement in which a party agrees to stop an activity without admitting fault.', 'The company entered a consent decree to resolve the regulator’s complaint.'],
  ['Whistleblower', 'A person who reports illegal or unethical conduct within an organization.', 'The whistleblower reported the accounting fraud to regulators.'],
  ['Anti-Trust', 'Laws designed to promote fair competition and prevent monopolies.', 'The merger faced anti-trust scrutiny over its impact on competition.'],
  ['Compliance', 'Adhering to laws, regulations, and internal policies.', 'The compliance team reviewed all vendor contracts for regulatory issues.'],
];
